'use strict';
const seed=[
['hotel','Hotel Ariston','Hotellet','⌂',45.46092,9.18116,'Largo del Carrobbio 2','Vårt högkvarter! Här landar shoppingpåsarna och här börjar nästa äventyr.','https://www.aristonhotel.com/'],
['torino','Via Torino','Shopping','🛍',45.4619,9.1843,'Via Torino','Bara en liten titt… sa ingen av oss. En shoppingpromenad nära hotellet med gott om anledningar att stanna.','https://www.yesmilano.it/esplora/luoghi/torino'],
['galleria','Galleria Vittorio Emanuele II','Shopping','✨',45.4658,9.1900,'Piazza del Duomo','Fönstershoppa med filmstjärnekänsla. Lyft blicken: här är själva shoppinggallerian också sevärdheten.','https://www.yesmilano.it/en/neighborhoods'],
['como','10 Corso Como','Shopping','👜',45.4835,9.1876,'Corso Como 10','Mode, design och konst i samma stopp. Perfekt för vår mest sofistikerade ”den där behöver jag”-blick.','https://10corsocomo.com/it/blogs/stores/milano'],
['brera','Brera','Shopping','🌷',45.4715,9.1875,'Via Brera • områdespunkt','Ta en sväng bland gränderna och låt nyfikenheten bestämma. Dagens uppdrag: hitta något som känns helt rätt.','https://www.yesmilano.it/en/neighborhoods'],
['luini','Luini','Mat & fika','🥟',45.4665,9.1916,'Via Santa Radegonda 16','Panzerotti-paus! Små fyllda godsaker med stor potential att bli resans ”vi tar en till”.','https://www.luini.it/storia.html'],
['sarpi','Chinatown / Via Paolo Sarpi','Mat & fika','🥢',45.4839,9.1785,'Via Paolo Sarpi','En smakpromenad med många frestelser. Vi delar på något gott – och beställer lite till om det behövs.','https://business.yesmilano.it/system/files/allegati/paragrafi/31877/Mappa%20Quartieri_Digital-versione-aprile-2024.pdf'],
['navigli','Navigli i kvällsljus','Aperitivo','🥂',45.4502,9.1679,'Alzaia Naviglio Grande • områdespunkt','Kanaler, kvällsljus och en skål för oss. Strosa först och välj sedan ett ställe som ser riktigt mysigt ut.','https://www.yesmilano.it/en/neighborhoods'],
['duomo','Duomos takterrasser','Upplevelser','⛪',45.4642,9.1916,'Piazza del Duomo','Milano från sin bästa sida: ovanifrån! Ett stopp för wow-känsla och en obligatorisk trio-selfie. Kolla biljetter och entré i förväg.','https://www.duomomilano.it/en/art-and-culture/the-terraces/'],
['spa','QC Spa Milano','Upplevelser','🫧',45.4524,9.2035,'Piazzale Medaglie d’Oro 2','När shoppingbenen röstar för semester: varma bad och skön återhämtning. Kolla bokning och villkor innan vi packar badkläderna.','https://www.qcterme.com/useful-information-milano-qr-code']
].map(([id,name,category,icon,lat,lng,address,description,source])=>({id,name,category,icon,lat,lng,address,description,source}));
seed.push(...(typeof extraPlaces!=='undefined'?extraPlaces:[]));
const $=s=>document.querySelector(s), esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const key='sistertrip-milano-v1';let state={custom:[],done:{},route:[],wants:{Malin:[],Louise:[],Elin:[]}},category='Alla',map,markers=new Map(),position,locationMarker,accuracyCircle,picked,toastTimer,photoDB;
try{const raw=JSON.parse(localStorage.getItem(key));if(raw)state=validate(raw);}catch{setTimeout(()=>toast('Kunde inte läsa sparad resa. En ny vy visas.'),100);}
function validate(s){if(!s||!Array.isArray(s.custom)||!Array.isArray(s.route)||!s.done||typeof s.done!=='object')throw Error('Ogiltig backup');const allowed=['Shopping','Outlets','Restauranger','Mat & fika','Aperitivo','Upplevelser'];for(const p of s.custom){if(typeof p.id!=='string'||!p.id.startsWith('custom-')||typeof p.name!=='string'||typeof p.description!=='string'||typeof p.address!=='string'||!allowed.includes(p.category)||!Number.isFinite(p.lat)||!Number.isFinite(p.lng)||Math.abs(p.lat)>90||Math.abs(p.lng)>180)throw Error('Ogiltig plats');p.source='';p.icon='📍';}const ids=new Set([...seed,...s.custom].map(p=>p.id));return {custom:s.custom,done:Object.fromEntries(Object.entries(s.done).filter(([id,v])=>ids.has(id)&&v===true)),route:[...new Set(s.route)].filter(id=>ids.has(id)&&id!=='hotel')};}
const places=()=>[...seed,...state.custom], get=id=>places().find(p=>p.id===id);
function save(){try{localStorage.setItem(key,JSON.stringify(state));}catch{toast('Kunde inte spara på enheten. Exportera en säkerhetskopia.');}render();}
function toast(t){$('#toast').textContent=t;$('#toast').style.display='block';clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('#toast').style.display='none',4500);}
function filtered(){const q=$('#search').value.toLocaleLowerCase('sv');return places().filter(p=>(category==='Alla'||category==='Avbockat'&&state.done[p.id]||p.category===category)&&`${p.name} ${p.description} ${p.address} ${p.tag||''} ${p.tip||''}`.toLocaleLowerCase('sv').includes(q));}
function render(){const cats=[['Alla','♡'],['Shopping','🛍'],['Outlets','🏷'],['Restauranger','🍝'],['Mat & fika','🥟'],['Aperitivo','🥂'],['Upplevelser','✨'],['Hotellet','⌂'],['Avbockat','✓']];$('#categories').innerHTML=cats.map(([c,i])=>`<button data-category="${c}" class="${c===category?'active':''}" aria-pressed="${c===category}">${i} ${c} <small>${c==='Alla'?places().length:c==='Avbockat'?Object.values(state.done).filter(Boolean).length:places().filter(p=>p.category===c).length}</small></button>`).join('');const list=filtered();$('#list-title').textContent=category==='Alla'?'Alla våra favoriter':category;$('#result-count').textContent=`${list.length} platser`;$('#total').textContent=places().length;$('#done-count').textContent=Object.values(state.done).filter(Boolean).length;$('#cards').innerHTML=list.map(p=>`<article class="card ${state.done[p.id]?'completed':''}" id="card-${esc(p.id)}"><div class="card-top"><span class="place-icon">${p.icon}</span><div><span class="tag">${esc(p.category)} ${state.done[p.id]?'• AVBOCKAT':''}</span><h3>${esc(p.name)}</h3><span class="address">⌖ ${esc(p.address)}</span></div></div><p>${esc(p.description)}</p>${p.tag?`<span class="place-badge">${esc(p.tag)}</span>`:''}${p.tip?`<p class="place-tip">♡ ${esc(p.tip)}</p>`:''}<div class="card-actions"><button class="fav-button" data-fav="${esc(p.id)}">♡ Potentiell rutt</button><button data-map="${esc(p.id)}">Visa på karta ↗</button>${p.id!=='hotel'&&!p.excursion?`<button class="${state.route.includes(p.id)?'in-route':''}" data-route="${esc(p.id)}">${state.route.includes(p.id)?'− Ur rutten':'+ Till rutten'}</button>`:''}<button class="done-button" data-done="${esc(p.id)}">${state.done[p.id]?'✓ Ångra':'○ Bocka av'}</button>${p.source?`<a href="${esc(p.source)}" target="_blank" rel="noopener">Källa ↗</a>`:''}</div>${state.done[p.id]?`<label class="upload">📷 Lägg till bildbevis<input type="file" accept="image/*" data-photo="${esc(p.id)}" hidden></label><div class="photos" data-gallery="${esc(p.id)}"></div>`:''}</article>`).join('')||'<div class="empty">Inga platser här ännu. Nästa minne väntar på er! ♡</div>';renderRoute();renderMarkers(list);renderPhotos();addNavigation();}
function renderRoute(){
 $('#route-count').textContent=`${state.route.length} stopp`;
 $('#route-list').innerHTML=state.route.map((id,i)=>`<li><span>${i+1}. ${esc(get(id).name)}</span><button data-up="${id}" aria-label="Flytta upp ${esc(get(id).name)}" ${i===0?'disabled':''}>↑</button><button data-down="${id}" aria-label="Flytta ner ${esc(get(id).name)}" ${i===state.route.length-1?'disabled':''}>↓</button><button data-route="${id}" aria-label="Ta bort ${esc(get(id).name)} ur rutten">×</button></li>`).join('')||'<li><span>Lägg till ett första stopp från platskorten.</span></li>';
 $('#route-links').innerHTML=state.route.length?'<button class="route-link" id="show-walk">Visa gångvägen på kartan ♡</button>':'';
 if($('#show-walk'))$('#show-walk').onclick=()=>drawWalk(plannedStops(),'Vår lilla runda');
 $('#clear-route').disabled=!state.route.length;
 const signature=JSON.stringify(plannedStops());
 if(planSignature!==signature){clearWalk();planSignature=signature;}
}
function plannedStops(){return [$('#from-location').checked&&position?{name:'Här är vi',...position}:get('hotel'),...state.route.map(get)];}
function renderMarkers(list){if(!map)return;for(const m of markers.values())map.removeLayer(m);markers.clear();const shown=places();for(const p of shown){const n=state.route.indexOf(p.id);const icon=L.divIcon({className:`pin ${p.id==='hotel'?'hotel':''}`,html:pinSymbol(p,n),iconSize:[32,32],iconAnchor:[16,16]});const box=document.createElement('div');const title=document.createElement('strong');title.textContent=p.name;box.append(title,document.createElement('br'),document.createTextNode(p.address));if(p.id!=='hotel'&&!p.excursion){const b=document.createElement('button');b.textContent=state.route.includes(p.id)?'Ta ur rutten':'+ Till rutten';b.onclick=()=>toggleRoute(p.id);box.append(document.createElement('br'),b);}markers.set(p.id,L.marker([p.lat,p.lng],{icon,title:p.name,alt:p.name}).addTo(map).bindPopup(box));}}
function showMap(id){if(!map){toast('Kartan är inte laddad. Kontrollera internetanslutningen.');return;}const p=get(id);if(!markers.has(id))renderMarkers(places());map.setView([p.lat,p.lng],16);markers.get(id)?.openPopup();$('#map').scrollIntoView({behavior:'smooth',block:'center'});}
function toggleRoute(id){if(get(id)?.excursion){toast('Den här utflykten kräver transport och läggs inte i gångrundan. Se platsens besöksinformation.');return;}state.route=state.route.includes(id)?state.route.filter(x=>x!==id):[...state.route,id];save();}
document.addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;const d=b.dataset;if(d.category){category=d.category;render();}if(d.fav){state.favorites=state.favorites||[];state.favorites=state.favorites.includes(d.fav)?state.favorites.filter(x=>x!==d.fav):[...state.favorites,d.fav];save();}if(d.want){const [n,id]=d.want.split('|');state.wants=state.wants||{Malin:[],Louise:[],Elin:[]};state.wants[n]=state.wants[n]||[];state.wants[n]=state.wants[n].includes(id)?state.wants[n].filter(x=>x!==id):[...state.wants[n],id];save();}if(d.map)showMap(d.map);if(d.route)toggleRoute(d.route);if(d.done){state.done[d.done]=!state.done[d.done];save();if(state.done[d.done])toast('Ett nytt minne! Lägg gärna till ett bildbevis.');}if(d.up||d.down){const id=d.up||d.down,i=state.route.indexOf(id),j=i+(d.up?-1:1);if(j>=0&&j<state.route.length){[state.route[i],state.route[j]]=[state.route[j],state.route[i]];save();}}});
$('#search').oninput=render;$('#discover').onclick=()=>$('#explore').scrollIntoView({behavior:'smooth'});$('#hotel').onclick=()=>showMap('hotel');$('#clear-route').onclick=()=>{state.route=[];save();};$('#from-location').onchange=()=>{if($('#from-location').checked&&!position){$('#from-location').checked=false;toast('Tryck på ”Var är vi?” först.');}renderRoute();};
$('#locate').onclick=()=>{if(!navigator.geolocation){toast('Den här webbläsaren stöder inte platsvisning.');return;}toast('Hämtar er position…');navigator.geolocation.getCurrentPosition(p=>{position={lat:p.coords.latitude,lng:p.coords.longitude};if(map){if(locationMarker)map.removeLayer(locationMarker);if(accuracyCircle)map.removeLayer(accuracyCircle);locationMarker=L.circleMarker([position.lat,position.lng],{radius:8,color:'#fff',weight:3,fillColor:'#2376b7',fillOpacity:1}).addTo(map).bindPopup('Här är vi!');accuracyCircle=L.circle([position.lat,position.lng],{radius:p.coords.accuracy,color:'#2376b7',weight:1,fillOpacity:.08}).addTo(map);map.setView([position.lat,position.lng],15);}$('#map-note').textContent=`Er position uppdaterad ${new Date().toLocaleTimeString('sv-SE')}. Noggrannhet cirka ${Math.round(p.coords.accuracy)} m. Tryck igen för att uppdatera.`;renderRoute();toast('Er position är markerad i blått.');},e=>toast(e.code===1?'Tillåt platsåtkomst i webbläsaren för att visa er position.':'Positionen kunde inte hämtas. Försök igen utomhus.'),{enableHighAccuracy:true,timeout:15000,maximumAge:10000});};
$('#add').onclick=()=>{const f=$('#place-form');f.reset();f.elements.lat.value=picked?.lat??'';f.elements.lng.value=picked?.lng??'';$('#place-dialog').showModal();};$('#close-dialog').onclick=()=>$('#place-dialog').close();$('#place-form').onsubmit=e=>{e.preventDefault();const f=new FormData(e.target);state.custom.push({id:'custom-'+crypto.randomUUID(),name:f.get('name').trim(),category:f.get('category'),description:f.get('description').trim(),address:f.get('address').trim(),lat:Number(f.get('lat')),lng:Number(f.get('lng')),source:'',icon:'📍'});category='Alla';$('#search').value='';save();$('#place-dialog').close();toast('En ny favorit är sparad!');};
function openDB(){return new Promise((resolve,reject)=>{const r=indexedDB.open('sistertrip-photos',1);r.onupgradeneeded=()=>r.result.createObjectStore('photos',{keyPath:'id'});r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error);});}
async function db(action,value){const database=await photoDB;return new Promise((resolve,reject)=>{const tx=database.transaction('photos',action==='getAll'?'readonly':'readwrite');const r=tx.objectStore('photos')[action](value);tx.oncomplete=()=>resolve(r.result);tx.onerror=()=>reject(tx.error);});}
async function renderPhotos(){try{const rows=await db('getAll');document.querySelectorAll('[data-gallery]').forEach(el=>{el.replaceChildren();rows.filter(p=>p.place===el.dataset.gallery).forEach(p=>{const box=document.createElement('div');box.className='photo';const img=document.createElement('img');img.src=p.data;img.alt='Bildbevis från '+get(p.place)?.name;img.onclick=()=>{const w=window.open('about:blank','_blank');if(w){w.opener=null;const full=w.document.createElement('img');full.src=p.data;full.style.maxWidth='100%';w.document.body.append(full);}};const del=document.createElement('button');del.textContent='×';del.setAttribute('aria-label','Ta bort bildbevis');del.onclick=async()=>{if(confirm('Ta bort det här bildbeviset?')){try{await db('delete',p.id);renderPhotos();}catch{toast('Kunde inte ta bort bilden.');}}};box.append(img,del);el.append(box);});});}catch{}}
async function compress(file){if(!file.type.startsWith('image/'))throw Error('Välj en bildfil.');if(file.size>25000000)throw Error('Bilden är för stor. Välj en bild under 25 MB.');const bitmap=await createImageBitmap(file);const ratio=Math.min(1,1400/Math.max(bitmap.width,bitmap.height));const canvas=document.createElement('canvas');canvas.width=Math.round(bitmap.width*ratio);canvas.height=Math.round(bitmap.height*ratio);canvas.getContext('2d').drawImage(bitmap,0,0,canvas.width,canvas.height);bitmap.close();return canvas.toDataURL('image/jpeg',.82);}
document.addEventListener('change',async e=>{if(!e.target.dataset.photo||!e.target.files[0])return;try{const data=await compress(e.target.files[0]);await db('put',{id:crypto.randomUUID(),place:e.target.dataset.photo,data});await renderPhotos();toast('Bildbevis sparat!');}catch(err){toast('Kunde inte spara bilden. Prova en mindre JPG- eller PNG-bild.');}});
$('#export').onclick=async()=>{try{const photos=await db('getAll');const blob=new Blob([JSON.stringify({version:1,...state,photos})],{type:'application/json'});const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='sistertrip-backup.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),30000);}catch{toast('Kunde inte skapa säkerhetskopian.');}};$('#import').onclick=()=>$('#import-file').click();$('#import-file').onchange=async e=>{try{const file=e.target.files[0];if(!file)return;const raw=JSON.parse(await file.text()),next=validate(raw);if(!Array.isArray(raw.photos)||raw.photos.some(p=>typeof p.id!=='string'||typeof p.place!=='string'||typeof p.data!=='string'||!/^data:image\/(jpeg|png|webp);base64,/.test(p.data)))throw Error();if(!confirm('Läsa in resan från säkerhetskopian? Nuvarande rutt och avbockningar ersätts. Befintliga bilder behålls.'))return;for(const p of raw.photos)await db('put',p);state=next;save();toast('Säkerhetskopian är inläst.');}catch{toast('Kunde inte läsa in filen. Välj en Sistertrip-säkerhetskopia.');}finally{e.target.value='';}};
photoDB=openDB();photoDB.catch(()=>toast('Bildlagring är inte tillgänglig i den här webbläsaren.'));
if(window.L){map=L.map('map').setView([45.465,9.185],14);const tiles=L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{attribution:'&copy; <a href="https://www.openstreetmap.org/copyright">OpenStreetMap</a>',maxZoom:19}).addTo(map);tiles.on('tileerror',()=>{$('#map-note').textContent='Kartbilder kunde inte laddas. Kontrollera internetanslutningen. Försök ladda om kartan när anslutningen fungerar.';});map.on('click',e=>{picked=e.latlng;toast('Kartpunkt vald. Tryck på ”Egen plats” för att spara den.');});}else{$('#map').innerHTML='<div class="empty">Kartan kunde inte laddas. Kontrollera internet och ladda om sidan. Platslistan fungerar fortfarande.</div>';}
function showExcursion(id){const p=get(id);showMap(id);const dialog=document.createElement('dialog');const title=document.createElement('h2');title.textContent=p.name;const note=document.createElement('p');note.textContent=p.tip;const link=document.createElement('a');link.className='route-link';link.href=p.source;link.target='_blank';link.rel='noopener';link.textContent='Transport och besöksinfo hos outletens webbplats ↗';const close=document.createElement('button');close.textContent='Stäng';close.onclick=()=>{dialog.close();dialog.remove();};dialog.append(title,note,link,close);document.body.append(dialog);dialog.showModal();}
async function directionsFromHere(id){
 try{await locateHere();await drawWalk([{name:'Här är vi',...position},get(id)],'Gångväg till '+get(id).name);}
 catch(e){toast(e.message);}
}
function addNavigation(){document.querySelectorAll('.card-actions').forEach(actions=>{const id=actions.querySelector('[data-map]').dataset.map;const button=document.createElement('button');button.textContent=get(id).excursion?'↗ Transport & besöksinfo':'◎ Gå hit från där vi är';button.onclick=()=>get(id).excursion?showExcursion(id):directionsFromHere(id);actions.prepend(button);});};
$('#from-location').onchange=async()=>{
 if(!$('#from-location').checked){renderRoute();return;}
 $('#from-location').disabled=true;
 try{await locateHere();renderRoute();}
 catch(e){$('#from-location').checked=false;renderRoute();toast(e.message);}
 finally{$('#from-location').disabled=false;}
};
$('#locate').onclick=()=>locateHere().catch(e=>toast(e.message));
let walkLayer,walkController,walkRequest=0,planSignature;
function clearWalk(){walkRequest++;walkController?.abort();if(walkLayer&&map)map.removeLayer(walkLayer);walkLayer=null;$('#walk-result').replaceChildren();}
function pinSymbol(p,n){
 const paths={'Shopping':'<path d="M5 8h14l-1 12H6L5 8z M9 8V6a3 3 0 0 1 6 0v2"/>','Mat & fika':'<path d="M6 3v7m-3-7v5a3 3 0 0 0 6 0V3M6 11v10M17 3v18m0-18c-5 4-5 10 0 10"/>','Aperitivo':'<path d="M7 3h10l-1 7a4 4 0 0 1-8 0L7 3zm5 11v7m-4 0h8"/>','Upplevelser':'<path d="m12 3 2.8 5.7 6.2.9-4.5 4.4 1.1 6.2-5.6-3-5.6 3 1.1-6.2L3 9.6l6.2-.9L12 3z"/>','Hotellet':'<path d="m3 11 9-8 9 8M6 9v12h12V9m-9 12v-8h6v8"/>'};
 return `<svg viewBox="0 0 24 24" aria-hidden="true" fill="none" stroke="currentColor" stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round">${paths[p.category==='Outlets'?'Shopping':p.category==='Restauranger'?'Mat & fika':p.category]||paths.Upplevelser}</svg>${n>=0?`<span class="pin-order">${n+1}</span>`:''}`;
}
function locateHere(){
 toast('Hämtar er position…');
 return new Promise((resolve,reject)=>{
  if(!navigator.geolocation)return reject(Error('Webbläsaren stöder inte platsåtkomst.'));
  navigator.geolocation.getCurrentPosition(p=>{
   position={lat:p.coords.latitude,lng:p.coords.longitude};
   if(map){if(locationMarker)map.removeLayer(locationMarker);if(accuracyCircle)map.removeLayer(accuracyCircle);locationMarker=L.circleMarker([position.lat,position.lng],{radius:8,color:'#fff',weight:3,fillColor:'#2376b7',fillOpacity:1}).addTo(map).bindPopup('Här är vi!');accuracyCircle=L.circle([position.lat,position.lng],{radius:p.coords.accuracy,color:'#2376b7',weight:1,fillOpacity:.08}).addTo(map);map.setView([position.lat,position.lng],15);}
   $('#map-note').textContent=`Er blå position uppdaterades ${new Date().toLocaleTimeString('sv-SE')}. Noggrannhet cirka ${Math.round(p.coords.accuracy)} m. Alla platser visas i rosa.`;
   resolve(position);
  },e=>reject(Error(e.code===1?'Tillåt platsåtkomst i webbläsaren och försök igen.':'Positionen kunde inte hämtas. Försök igen utomhus.')),{enableHighAccuracy:true,timeout:15000,maximumAge:0});
 });
}
function decodeShape(str){let index=0,lat=0,lng=0,result=[];function number(){let sum=0,shift=0,byte;do{if(index>=str.length||shift>30)throw Error('Ogiltig väggeometri');byte=str.charCodeAt(index++)-63;sum|=(byte&31)<<shift;shift+=5;}while(byte>=32);return sum&1?~(sum>>1):sum>>1;}while(index<str.length){lat+=number();lng+=number();result.push([lat/1e6,lng/1e6]);}return result;}
async function drawWalk(stops,title){
 clearWalk();if(stops.some(p=>p.excursion)){toast('Utflykter utanför Milano kräver transport. Se platsens besöksinformation.');return;}if(!map){toast('Ladda kartan först för att visa gångvägen.');return;}
 if(stops.length<2)return;
 if(stops.length>20){toast('Välj högst 19 stopp per runda.');return;}
 const request=walkRequest;walkController=new AbortController();const controller=walkController;
 $('#walk-result').textContent='Hittar en gångväg längs gator och gångstråk…';
 const timeout=setTimeout(()=>controller.abort(),20000);
 try{
  const payload={locations:stops.map(p=>({lat:p.lat,lon:p.lng,type:'break'})),costing:'pedestrian',directions_options:{units:'kilometers',language:'sv-SE'}};
  const response=await fetch('https://valhalla1.openstreetmap.de/route?json='+encodeURIComponent(JSON.stringify(payload)),{signal:controller.signal});
  if(!response.ok)throw Error('Rutttjänsten kunde inte beräkna vägen.');
  const data=await response.json();if(request!==walkRequest)return;
  const trip=data.trip;if(!trip?.legs?.length||trip.status!==0)throw Error('Ingen gångväg hittades.');
  const lines=trip.legs.map(l=>decodeShape(l.shape));
  walkLayer=L.polyline(lines,{color:'#e83e8c',weight:6,opacity:1,lineCap:'round',lineJoin:'round'}).addTo(map);
  map.fitBounds(walkLayer.getBounds(),{padding:[35,35],maxZoom:16});
  const result=$('#walk-result');result.replaceChildren();
  const heading=document.createElement('h3');heading.textContent=title;
  const summary=document.createElement('p');summary.className='walk-summary';summary.textContent=`${trip.summary.length.toLocaleString('sv-SE',{maximumFractionDigits:1})} km · cirka ${Math.max(1,Math.round(trip.summary.time/60))} min till fots`;
  result.append(heading,summary);
  trip.legs.forEach((leg,i)=>{const details=document.createElement('details');details.open=trip.legs.length===1;const label=document.createElement('summary');label.textContent=`${i+1}. ${stops[i].name} → ${stops[i+1].name}`;const steps=document.createElement('ol');for(const maneuver of leg.maneuvers||[]){const li=document.createElement('li');li.textContent=maneuver.instruction.replaceAll('the crosswalk','övergångsstället')+(maneuver.length>0?` (${Math.round(maneuver.length*1000)} m)`:'');steps.append(li);}details.append(label,steps);result.append(details);});
  const close=document.createElement('button');close.textContent='Dölj gångvägen';close.onclick=clearWalk;result.append(close);
  $('#map').scrollIntoView({behavior:'smooth',block:'center'});
 }catch(e){if(request!==walkRequest)return;$('#walk-result').textContent='Gångvägen kunde inte hämtas. Kontrollera internet och försök igen. Ingen väg visas förrän den har beräknats.';const retry=document.createElement('button');retry.textContent='Försök igen';retry.onclick=()=>drawWalk(stops,title);$('#walk-result').append(document.createElement('br'),retry);}
 finally{clearTimeout(timeout);}
}

render();






